package com.paracelsoft.teamsport.repository;

import java.math.BigInteger; 
import java.util.List;
import java.util.Map;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.querydsl.QuerydslPredicateExecutor;
import org.springframework.stereotype.Repository;

import com.paracelsoft.teamsport.entity.TeamRankPackagePrice;

/**
* Generated by Spring Data Generator on 16/03/2019
*/
@Repository
public interface TeamRankPackagePriceRepository extends JpaRepository<TeamRankPackagePrice, BigInteger>, JpaSpecificationExecutor<TeamRankPackagePrice>, QuerydslPredicateExecutor<TeamRankPackagePrice> {
	
	TeamRankPackagePrice findByRankPackagePriceId(BigInteger RankPriceId);
	
	List<TeamRankPackagePrice> findByTeamRankId(BigInteger teamRankId);
	
	@Modifying
	@Query(value="delete from team_rank_package_price where team_rank_id = :teamRankId", nativeQuery = true)
	void deleteOldTeamRankPackagePrice(BigInteger teamRankId);
	
	@Query(value="SELECT rank_package_price_value, rank_package_price_unit, rank_package_price_time \r\n" + 
			"FROM teamsport.team_rank_package_price WHERE team_rank_id = :teamRankId", nativeQuery = true)
	List<Map<String, Object>> findPackagePriceByTeamRankId(BigInteger teamRankId);
}
