package com.paracelsoft.teamsport.repository;

import java.math.BigInteger;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.querydsl.QuerydslPredicateExecutor;
import org.springframework.stereotype.Repository;

import com.paracelsoft.teamsport.entity.TeamRank;

/**
* Generated by Spring Data Generator on 16/03/2019 
*/
@Repository
public interface TeamRankRepository extends JpaRepository<TeamRank, BigInteger>, JpaSpecificationExecutor<TeamRank>, QuerydslPredicateExecutor<TeamRank> {

	TeamRank findByTeamRankIdAndIsActive(BigInteger teamRankId, int i);
	
	List<TeamRank> findByIsActive(int isActive); // Get all teamRank by isActive
}