package com.paracelsoft.teamsport.repository;

import java.math.BigInteger;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.querydsl.QuerydslPredicateExecutor;
import org.springframework.stereotype.Repository;

import com.paracelsoft.teamsport.entity.UserAchievement;

/**
* Generated by Spring Data Generator on 16/03/2019
*/
@Repository
public interface UserAchievementRepository extends JpaRepository<UserAchievement, BigInteger>, JpaSpecificationExecutor<UserAchievement>, QuerydslPredicateExecutor<UserAchievement> {
	
	List<UserAchievement> findByUserIdAndIsActive(BigInteger userId, int isActive);

	@Modifying
	@Query(value="delete from user_achievement where user_id = :userId", nativeQuery = true)
	void deleteByUserId(BigInteger userId);
}