package com.paracelsoft.teamsport.repository;

import java.math.BigInteger;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.querydsl.QuerydslPredicateExecutor;
import org.springframework.stereotype.Repository;

import com.paracelsoft.teamsport.entity.UserLogin;

/**
* Generated by Spring Data Generator on 16/03/2019
*/
@Repository
public interface UserLoginRepository extends JpaRepository<UserLogin, String>, JpaSpecificationExecutor<UserLogin>, QuerydslPredicateExecutor<UserLogin> {

	UserLogin findByUserIdAndIsActive(String userId, int i);

	Optional<UserLogin> findByUserNameAndIsActive(String userName, int i);
	
	Optional<UserLogin> findByUserIdAndIsActive(BigInteger userId, int i);

}
